name: glife
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.4
  firebase_storage: ^11.7.6
  intl: ^0.19.0
  image_picker: ^1.1.1
  firebase_auth: ^4.19.6
  google_sign_in: ^6.2.1


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets: 
    - assets/images/logo.jpeg
    - assets/images/character.jpeg
    - assets/images/sunglasses.jpg
    - assets/images/character_sunglasses.png
    - assets/images/character_sunglasses.jpeg